baseapp/urls.py
from django.urls import path
from .views import TaskList, TaskDeets, CreateTask, TaskUpdate, DeleteTask, LoginPage, RegistrationPage
from django.contrib.auth.views import LogoutView

#as_view method returns a callable view that takes a request and returns a response
urlpatterns = [
    path('', TaskList.as_view(), name = 'home'),
    path('logout/', LogoutView.as_view(next_page = 'loginpage'), name = 'logO'),

    #path('tasks/<int:pk>/', TaskDeets.as_view(), name = 'task'),
    path('add-task/', CreateTask.as_view(), name = 'add-task'),
    path('update-task/<int:pk>/', TaskUpdate.as_view(), name = 'update-task'),
    path('delete/task/<int:pk>/', DeleteTask.as_view(), name = 'delete.task'),
    path('login/', LoginPage.as_view(), name = "loginpage"),
    path('register/', RegistrationPage.as_view(), name = "regist")
    ]

"""
next_page is used to redirect the user to a particular page after logout.
"""

#tasks/1 gives 1st task, tasks/2 gives 2nd task and so on...

toDoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baseapp.urls'))
]

baseapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#each class defines a database table

class TodoTasks(models.Model):

    #class attributes define the database fields


    #use foreign key for many-to-one relationships

    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True, blank = True)

    #models.CASCADE signifies that whenever a user is deleted delete all the tasks too

    tasktitle = models.CharField(max_length = 200)
    completed = models.BooleanField(default = False)
    description = models.TextField(null = True, blank = True)
    creation = models.DateTimeField(auto_now_add = True) #add current date and time
    

    #string representation of object created
    def __str__(self):
        return self.tasktitle

    #metadata of class is given using Meta inner class
    class Meta:
        ordering = ['completed'] #order based on completed or not

baseapp/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import TodoTasks
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy 
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm #used for creating a new user to use my web application
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login

#logout functionality direct in urls.py
#reverse_lazy accepts view and returns an URL. Used for redirecting once form is submitted

# Create your views here.

class LoginPage(LoginView):
    template_name = 'baseapp/loginpage.html'
    fields = '__all__'
    redirect_authenticated_user = True #if already logged in, don't come here

    def get_success_url(self):
        return reverse_lazy('home')

class RegistrationPage(FormView):
    #formView is used to display and verify a Django form
    template_name = 'baseapp/registrationPage.html'
    form_class = UserCreationForm

    #redirect to home once user is signed up
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = form.save()

        #user successfully created
        if user is not None:
            login(self.request, user)
        return super(RegistrationPage, self).form_valid(form)

    #this is used if user is already logged in, registration page is not accessible and he/she/they are redirected to home

    def get(self, *args, **kwargs):

        #is_authenticated is attribute of User
        if self.request.user.is_authenticated:
            return redirect('home')

        #if user is not authenticated call super() implementation
        return super(RegistrationPage, self).get(*args, **kwargs)

#class-based view
class TaskList(LoginRequiredMixin, ListView):  #loginrequiredmixin restricts guests users. Should login

    """
    ListView is a generic class based view used to display a page representing a list of objects.
    self.object_list contains list of objects  that the view is operating upon
    By default listview looks for a template with "{model name}_list.html". Configure this in templates/baseapp

    """

    model = TodoTasks
    
    #used to change default object_list to name of our choice
    context_object_name = 'tasks'

    template_name = 'baseapp/listDemo.html'


    """
    to add extra content to our existing context, we need to
    override this method. Default implementation of this method adds the
    object being displayed to the template.
    """

    def get_context_data(self, **kwargs):
        #call base implementation to get context
        context = super().get_context_data(**kwargs)

        #to ensure each user sees his/her own tasks
        context['tasks'] = context['tasks'].filter(user=self.request.user)

        #to show how many incomplete tasks are present
        context['incompletetasks'] = context['tasks'].filter(completed = False).count()

        #for search functionality

        #get word from the searchbar
        search_items = self.request.GET.get('searchbar') or ''

        #if search input exists, filter accordingly
        if search_items:
            context['tasks'] = context['tasks'].filter(tasktitle__icontains = search_items)
        
        context['searchitems'] = search_items
        return context
"""
DetailView returns information about a simple item(single model instance)
"""
class TaskDeets(LoginRequiredMixin, DetailView):

    #this view looks for {model_name}_detail.html in templates.
    model = TodoTasks

    context_object_name = 'task'

    #to override default template names like {}_detail and {}_list
    template_name = 'baseapp/detailDemo.html'


#createview is used for forms and need to do a database insertion of submission of form

class CreateTask(LoginRequiredMixin, CreateView):

    #looks for template with {{model}}_form.html
    model = TodoTasks

    #__all__ includes all fields under model class.

    fields = ['tasktitle', 'completed', 'description']

    #redirect
    success_url = reverse_lazy('home') #check url.py


    def form_valid(self, form):

        #user is the logged in user
        
        form.instance.user = self.request.user
        return super(CreateTask, self).form_valid(form)



#redisplays form if it has validation errors
#and save changes of the object to the database
"""
whenever we click on update it prepopulates the existing 
task data in 
the form

"""
class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = TodoTasks
    fields = '__all__'
    success_url = reverse_lazy('home')


"""
If request method is GET, view will display confirmation page or else
if it is POST, view will delete the object
"""

class DeleteTask(LoginRequiredMixin, DeleteView):
    model = TodoTasks
    context_object_name = 'thetask'
    success_url = reverse_lazy('home')
    template_name = 'baseapp/deleteDemo.html'

baseapp/templates/baseapp/deleteDemo.html
{% extends 'baseapp/maindesign.html' %}

{% block areablock %}

<div class = "bar">
    <a href = "{% url 'home' %}">&#8592; Go Back</a>
</div>
<div class = "formbody">
    <form method = "POST">
        {% csrf_token %}
        <p>Are you sure you want to delete this task?: {{thetask}}</p>
        <input class = "button" type = "submit" value="YES">
    </form>
</div>

{% endblock areablock %}

baseapp/templates/baseapp/detailDemo.html
<!--{{object}} instead of {{object_list}} used in todotasks_list.html-->

<!--default object is changed to task in views.py using context_object_name-->
{% extends 'baseapp/maindesign.html' %}

{% block areablock %}
<h1>Hello! Your {{task}}</h1>
{% endblock areablock %}

baseapp/templates/baseapp/listDemo.html
{% extends 'baseapp/maindesign.html' %}

{% block areablock %}

<div class = "bar">
    <div>
        <!--capitalize first letter-->
        <h1>Hello, {{request.user|title}}</h1>
        <h4><i>You have {{incompletetasks}} incomplete task{{ incompletetasks|pluralize:"s" }}</i></h4>
    </div>
    {% if request.user.is_authenticated %} 
    <!--<p>{{request.user}}</p>to display username-->
    <a href="{% url 'logO' %}">Logout</a>
    {% else %}
        <a href="{% url 'loginpage' %}">Login</a>
        <hr>
    {% endif %}
</div>

<hr>

<div id = "searchbar-wrap">
    <form method = "GET" style = "margin-top:20px; display: flex;">
        <input type = "text" name = "searchbar" value = "{{search_items}}">
        <input class = "button" type = "submit" value = "search">
    </form>
    <a href = "{% url 'add-task' %}">ADD</a>
</div>

<br><br>


<div class = "item-wrapper">
    {% for task in tasks %} <!--check models.py for object_list explanation-->
    <div class = "task-wrapper">
        {% if task.completed %}
        <div class = "title">
            <div class = "complete-icon"></div>
            <i><a href = "{% url 'update-task' task.id %}">{{task}}</a></i>
        </div>
        <a class="deleteTask" href = "{% url 'delete.task' task.id %}">&#215;</a>
        {% else %}
        <div class = "title">
            <div class = "incomplete-icon"></div>
            <a href = "{% url 'update-task' task.id %}">{{task}}</a>
        </div>
        <a class = "deleteTask" href = "{% url 'delete.task' task.id %}">&#215;</a>
        {% endif %}
</div>

{% empty %}
<h3>No tasks scheduled!</h3>
{% endfor %}

{% endblock areablock %}

baseapp/templates/baseapp/loginpage.html
{% extends 'baseapp/maindesign.html' %}
{% block areablock %}

<div class = "bar">
    <h1>Login to your account</h1>
</div>

<div class = "formbody">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class = "button" type = "submit" value = "Login">
    </form>
    <br>
    <hr>
    <p>Don't have an account? <a href = "{% url 'regist' %}">Click here to register</a></p>
</div>

{% endblock areablock %}

baseapp/templates/baseapp/maindesign.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>To-Do List</title>
        <meta name="viewport" content = "width=device-width, initial-scale=1">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300&family=Ysabeau+SC:wght@300&display=swap" rel="stylesheet">
    </head>

    <style>
        body {
            background-color: blanchedalmond;
            font-family: 'Fira Sans', sans-serif;
            padding-top: 40px;
        }

        .container {
            max-width: 550px;
            margin: auto;
            background-color: white;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21);
            box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        }

        h1,h2,h3,h4,h5,h6 {
            font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }

        a,p {
            color: black;
        }

        .bar {
            display: flex;
            padding: 16px;
            justify-content: space-between;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(to right, #0066ff, lightblue);
        }

        .bar a{
            text-decoration: none;
            color: white;
        }

        .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px;
            border-top: 1px solid rgb(226, 226, 226);
        }

        .title {
            display: flex;
        }

        .title a {
            margin-left: 10px;
            color: rgb(61, 4, 97);
        }

        .complete-icon {
            height: 20px;
            width: 20px;
            border-radius: 50%;
            background-color: green;
        }

        .incomplete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(219, 220, 221);
            border-radius: 50%;
        }

        .deleteTask {
            color: red;
            text-decoration: none;
            line-height: 0;
            font-size: 40px;
        }

        #searchbar-wrap {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
        }

        input[type=text], input[type=password], textarea {
            border: 1px solid #ff1212;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
        }

        label {
            padding-top: 10px;
            display: block;
        }

        .button {
            padding: 10px;
            font-size: 14px;
            cursor: pointer;
            text-decoration: none;
            background-color: #FAFAFA;
            border-radius: 5px;
        }

        .formbody {
            padding: 20px;
        }
        
    </style>
    <!--in master template the "block" tag
    is used. in all templates which inherit
    from the master template will give their
    own content in the block tags-->

    <!--in this example our block is called as areablock-->
    <body>
        <div class = "container">
            {% block areablock %}

            {% endblock areablock %}
        </div>
    </body>
</html>

baseapp/templates/baseapp/registrationPage.html
{% extends 'baseapp/maindesign.html' %}
{% block areablock %}

<div class = "bar">
    <h1>Create a new account</h1>
</div>

<div class = "formbody">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}
        <label>{{form.password1.label}}</label>
        {{form.password1}}
        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style = "margin-top:16px" class = "button" type = "submit" value = "Register">
    </form>
    <br>
    <hr>
    <p>Already have an account? <a href = "{% url 'loginpage' %}">Click here to sign-in</a></p>
</div>


{% endblock areablock %}

baseapp/templates/baseapp/todotasks_form.html
{% extends 'baseapp/maindesign.html' %}

{% block areablock %}

<div class = "bar">
    <a href = "{% url 'home' %}">&#8592; Go Back</a>
</div>

<div class = "formbody">
    <form method = "POST" action="">
        {% csrf_token %}
        <!--format the form as a paragraph-->
        {{form.as_p}} 
        <input class = "button" type = "submit" value = "Add Task">
    </form>
</div>
{% endblock areablock %}